// <auto-generated />
using System;
using AVMLabs.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AVMLabs.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260830075250_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AVMLabs.Api.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            City = "Dubai",
                            ClientName = "Al Noor Hospital",
                            ContactPerson = "Ahmed Khalid",
                            Country = "UAE",
                            Email = "ahmed@alnoor.ae",
                            IsActive = true,
                            Phone = "+971500000001"
                        },
                        new
                        {
                            ClientId = 2,
                            City = "Chennai",
                            ClientName = "Apollo Diagnostics",
                            ContactPerson = "Priya Menon",
                            Country = "India",
                            Email = "priya@apollo.in",
                            IsActive = true,
                            Phone = "+919840000002"
                        },
                        new
                        {
                            ClientId = 3,
                            City = "Doha",
                            ClientName = "Gulf Care Clinic",
                            ContactPerson = "Sara Ali",
                            Country = "Qatar",
                            Email = "sara@gulfcare.qa",
                            IsActive = true,
                            Phone = "+96550000003"
                        });
                });

            modelBuilder.Entity("AVMLabs.Api.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("ClientId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("AVMLabs.Api.Models.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SampleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TestId");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            TestId = 1,
                            IsActive = true,
                            Rate = 15.00m,
                            SampleType = "Blood",
                            TestCode = "CBC001",
                            TestName = "Complete Blood Count"
                        },
                        new
                        {
                            TestId = 2,
                            IsActive = true,
                            Rate = 25.00m,
                            SampleType = "Blood",
                            TestCode = "LFT001",
                            TestName = "Liver Function Test"
                        },
                        new
                        {
                            TestId = 3,
                            IsActive = true,
                            Rate = 25.00m,
                            SampleType = "Blood",
                            TestCode = "KFT001",
                            TestName = "Kidney Function Test"
                        },
                        new
                        {
                            TestId = 4,
                            IsActive = true,
                            Rate = 10.00m,
                            SampleType = "Urine",
                            TestCode = "URN001",
                            TestName = "Urine Routine"
                        },
                        new
                        {
                            TestId = 5,
                            IsActive = true,
                            Rate = 30.00m,
                            SampleType = "Blood",
                            TestCode = "THY001",
                            TestName = "Thyroid Profile"
                        });
                });

            modelBuilder.Entity("AVMLabs.Api.Models.WorkOrder", b =>
                {
                    b.Property<int>("WOId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WOId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("WODate")
                        .HasColumnType("datetime2");

                    b.HasKey("WOId");

                    b.HasIndex("ClientId");

                    b.ToTable("WorkOrders");

                    b.HasData(
                        new
                        {
                            WOId = 1,
                            ClientId = 1,
                            Status = "Completed",
                            TotalAmount = 40.00m,
                            WODate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            WOId = 2,
                            ClientId = 2,
                            Status = "Pending",
                            TotalAmount = 35.00m,
                            WODate = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            WOId = 3,
                            ClientId = 3,
                            Status = "Completed",
                            TotalAmount = 30.00m,
                            WODate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AVMLabs.Api.Models.WorkOrderItem", b =>
                {
                    b.Property<int>("WOItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WOItemId"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("WOId")
                        .HasColumnType("int");

                    b.HasKey("WOItemId");

                    b.HasIndex("TestId");

                    b.HasIndex("WOId");

                    b.ToTable("WorkOrderItems");

                    b.HasData(
                        new
                        {
                            WOItemId = 1,
                            Quantity = 1,
                            Rate = 15.00m,
                            TestId = 1,
                            WOId = 1
                        },
                        new
                        {
                            WOItemId = 2,
                            Quantity = 1,
                            Rate = 25.00m,
                            TestId = 2,
                            WOId = 1
                        },
                        new
                        {
                            WOItemId = 3,
                            Quantity = 1,
                            Rate = 25.00m,
                            TestId = 3,
                            WOId = 2
                        },
                        new
                        {
                            WOItemId = 4,
                            Quantity = 1,
                            Rate = 10.00m,
                            TestId = 4,
                            WOId = 2
                        },
                        new
                        {
                            WOItemId = 5,
                            Quantity = 1,
                            Rate = 30.00m,
                            TestId = 5,
                            WOId = 3
                        });
                });

            modelBuilder.Entity("AVMLabs.Api.Models.Invoice", b =>
                {
                    b.HasOne("AVMLabs.Api.Models.Client", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AVMLabs.Api.Models.WorkOrder", b =>
                {
                    b.HasOne("AVMLabs.Api.Models.Client", "Client")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AVMLabs.Api.Models.WorkOrderItem", b =>
                {
                    b.HasOne("AVMLabs.Api.Models.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AVMLabs.Api.Models.WorkOrder", "WorkOrder")
                        .WithMany("Items")
                        .HasForeignKey("WOId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("AVMLabs.Api.Models.Client", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("AVMLabs.Api.Models.WorkOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
